### ISSUE TITLE
Server player connetct-disconnect log and player list

### ISSUE THREAD

**Issue by diablobash** [BeepIsla/fake-stattrak#32]
Hello, I'm trying to fake stattrak on multiple accounts. I'm spreading this over a long process so that I don't get stuck on the limit. The player on the server sometimes gets disconnected. So is it possible to log these disconnections and connections? Also, is it possible to get the instant list of players on the server?

**Comment by BeepIsla** [comment]
Its probably the bots/server disconnecting from Steam due to the connection breaking or something and never re-authenticating properly.

There is no way to get a list of players currently on the server, at best you could implement the master server heartbeat but it would just tell you player count and not *who* exactly is on the server

**Comment by diablobash** [comment]
thanks for your answer
